[workspace]
resolver = "2"
members = [
  "contracts/governance",
  "contracts/insurance",
  "contracts/teachlink",
]

[workspace.package]
edition = "2021"
repository = "https://github.com/rinafcode/teachLink_contract"
license = "MIT"

[workspace.dependencies]
soroban-sdk = "25.0.0-rc.2"

[workspace.lints.clippy]
all = { level = "allow", priority = -1 }
pedantic = { level = "allow", priority = -2 }

[workspace.lints.rust]
unsafe_code = "deny"
